const eventData = [
  {
    id: 1,
    title: "Nairobi International Choral Festival",
    imageSrc: "/Event1.png",
    altText: "choral",
    date: "Sun, Apr 28",
    location: "The Dome, ASK Showground",
    price: "From KES 500",
  },
  {
    id: 2,
    title: "Nairobi Colour Festival",
    imageSrc: "/Event2.png",
    altText: "color",
    date: "Sat, Apr 20",
    location: "Carnivore Grounds",
    price: "From KES 800",
  },
  {
    id: 3,
    title: "Raha Fest 2024",
    imageSrc: "/Event3.png",
    altText: "raha",
    date: "Sat, Mar 30",
    location: "Uhuru Gardens",
    price: "From KES 6000",
  },
  {
    id: 4,
    title: "RX-Fest Amapiano Edition",
    imageSrc: "/Event4.png",
    altText: "rx",
    date: "Sat, Apr 27",
    location: "Kasarani Sports Stadium",
    price: "From KES 700",
  },
  {
    id: 5,
    title: "Solid Soul",
    imageSrc: "/Event5.svg",
    altText: "soul",
    date: "Fri, Apr 26",
    location: "Carnivore Restaurant - Simba Saloon",
    price: "From KES 1,500",
  },
  {
    id: 6,
    title: "Passionate Pages Flavoured by Manyatta Cider",
    imageSrc: "/Event6.svg",
    altText: "cider",
    date: "Sat, Mar 23",
    location: "New Muthaiga Mall, Thigiri Ridge",
    price: "From KES 1000",
  },
  {
    id: 7,
    title: "Sunday Beats",
    imageSrc: "/Event7.svg",
    altText: "beats",
    date: "Every Sun, Feb 25 to May 26",
    location: "Nairobi Street Kitchen",
    price: "Free",
  },
  {
    id: 8,
    title: "Kiota School Family Outdoor Movie Matinee",
    imageSrc: "/Event8.svg",
    altText: "kiota",
    date: "Sun, Apr 28",
    location: "The Dome, ASK Showground",
    price: "From KES 500",
  },
];

export default eventData;
