import EventData from "../../types/event";

const eventData: EventData[] = [
  {
    id: 1,
    title: "Nairobi International Choral Festival",
    imageSrc: "/Event1.png",
    altText: "choral",
    date: "Sun, Apr 28",
    location: "The Dome, ASK Showground",
    price: "From KES 500",
    earlyBirdTicket: 400,
    advancedTicket: 450,
    gateTicket: 500,
    timeOfEvent: "18:00",
    earlyBirdStatus: true,
    gateStatus: true,
    advancedStatus: true,
  },
  {
    id: 2,
    title: "Nairobi Colour Festival",
    imageSrc: "/Event2.png",
    altText: "color",
    date: "Sat, Apr 20",
    location: "Carnivore Grounds",
    price: "From KES 800",
    earlyBirdTicket: 700,
    advancedTicket: 750,
    gateTicket: 800,
    timeOfEvent: "15:00",
    earlyBirdStatus: false,
    gateStatus: true,
    advancedStatus: false,
  },
  {
    id: 3,
    title: "Raha Fest 2024",
    imageSrc: "/Event3.png",
    altText: "raha",
    date: "Sat, Mar 30",
    location: "Uhuru Gardens",
    price: "From KES 6000",
    earlyBirdTicket: 5500,
    advancedTicket: 5800,
    gateTicket: 6000,
    timeOfEvent: "20:00",
    earlyBirdStatus: true,
    gateStatus: true,
    advancedStatus: true,
  },
  {
    id: 4,
    title: "RX-Fest Amapiano Edition",
    imageSrc: "/Event4.png",
    altText: "rx",
    date: "Sat, Apr 27",
    location: "Kasarani Sports Stadium",
    price: "From KES 700",
    earlyBirdTicket: 600,
    advancedTicket: 650,
    gateTicket: 700,
    timeOfEvent: "21:30",
    earlyBirdStatus: false,
    gateStatus: true,
    advancedStatus: false,
  },
  {
    id: 5,
    title: "Solid Soul",
    imageSrc: "/Event5.svg",
    altText: "soul",
    date: "Fri, Apr 26",
    location: "Carnivore Restaurant - Simba Saloon",
    price: "From KES 1,500",
    earlyBirdTicket: 1300,
    advancedTicket: 1400,
    gateTicket: 1500,
    timeOfEvent: "19:00",
    earlyBirdStatus: true,
    gateStatus: false,
    advancedStatus: true,
  },
  {
    id: 6,
    title: "Passionate Pages Flavoured by Manyatta Cider",
    imageSrc: "/Event6.svg",
    altText: "cider",
    date: "Sat, Mar 23",
    location: "New Muthaiga Mall, Thigiri Ridge",
    price: "From KES 1000",
    earlyBirdTicket: 900,
    advancedTicket: 950,
    gateTicket: 1000,
    timeOfEvent: "16:45",
    earlyBirdStatus: false,
    gateStatus: true,
    advancedStatus: false,
  },
  {
    id: 7,
    title: "Sunday Beats",
    imageSrc: "/Event7.svg",
    altText: "beats",
    date: "Every Sun, Feb 25 to May 26",
    location: "Nairobi Street Kitchen",
    price: "Free",
    earlyBirdTicket: 3000,
    advancedTicket: 2000,
    gateTicket: 5000,
    timeOfEvent: "14:00",
    earlyBirdStatus: false,
    gateStatus: true,
    advancedStatus: false,
  },
  {
    id: 8,
    title: "Kiota School Family Outdoor Movie Matinee",
    imageSrc: "/Event8.svg",
    altText: "kiota",
    date: "Sun, Apr 28",
    location: "The Dome, ASK Showground",
    price: "From KES 500",
    earlyBirdTicket: 400,
    advancedTicket: 450,
    gateTicket: 500,
    timeOfEvent: "12:00",
    earlyBirdStatus: true,
    gateStatus: true,
    advancedStatus: true,
  },
];

export default eventData;
